services:
  postgres:
    image: postgres:latest
    container_name: incident_db
    environment:
      POSTGRES_DB: incidentdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
